Repository kmaengggong/AndCrowd-Frontend, pull requests merged in 2023-09, with the labels that each got.

#29 Feature/21-1: 모임 채팅
  andcrowd/package-lock.json
  andcrowd/package.json
  andcrowd/src/App.js
  andcrowd/src/components/.ChatRoom.js.icloud
  andcrowd/src/pages/and/AndChat.js
  andcrowd/src/pages/and/AndDetail.js
  andcrowd/src/pages/chat/ChatPage.js
  andcrowd/src/pages/chat/Chatroom copy.js
  andcrowd/src/pages/chat/Chatroom.js
  andcrowd/src/pages/chat/ChatroomUpdate.js
  andcrowd/src/pages/chat/NicknameInput.js
Labels: 임규빈

#37 Feature/28:피드 디자인 완료
  andcrowd/src/App.js
  andcrowd/src/components/Header.js
  andcrowd/src/components/ScrollToTop.js
  andcrowd/src/logo.svg
  andcrowd/src/pages/and/AndMember.js
  andcrowd/src/pages/and/AndMemberCreate.js
  andcrowd/src/pages/and/AndMemberDetail.js
  andcrowd/src/pages/and/AndMemberUpdate.js
  andcrowd/src/pages/and/AndScroll.js
  andcrowd/src/pages/and/cat.jpg
  andcrowd/src/pages/and/free-icon-show-more-button-with-three-dots-61140.png
  andcrowd/src/pages/and/shoes-8026038.jpg
  andcrowd/src/styles/Header.css
  andcrowd/src/styles/Login.css
  andcrowd/src/styles/and/Feed.css
Labels: 양현성

#41 Feature/11: 로그인, 회원가입 기능 구현
  andcrowd/package-lock.json
  andcrowd/package.json
  andcrowd/src/App.js
  andcrowd/src/components/Header.js
  andcrowd/src/components/isLogin.js
  andcrowd/src/components/route/PrivateRoute.js
  andcrowd/src/components/route/PublicRoute.js
  andcrowd/src/components/sign/IsValidAccessToken.js
  andcrowd/src/components/sign/Logout.js
  andcrowd/src/components/sign/NaverLogin.js
  andcrowd/src/components/sign/SignRoute.js
  andcrowd/src/components/sign/SignUpAuthNumber.js
  andcrowd/src/components/sign/SignUpNickname.js
  andcrowd/src/components/sign/SignUpPassword.js
  andcrowd/src/components/sign/SingUpEmail.js
  andcrowd/src/components/sign/isLogin.js
  andcrowd/src/components/user/GetUserId.js
  andcrowd/src/context/isLoginContext.js
  andcrowd/src/index.js
  andcrowd/src/pages/Home.js
  andcrowd/src/pages/Login.js
  andcrowd/src/pages/MyPage.js
  andcrowd/src/pages/Signup.js
  andcrowd/src/pages/Test.js
  andcrowd/src/pages/etc/Help.js
  andcrowd/src/pages/etc/NotFound.js
  andcrowd/src/pages/etc/Team.js
  andcrowd/src/pages/user/Login.js
  andcrowd/src/pages/user/MyPage.js
  andcrowd/src/pages/user/Signup.js
Labels: 김명호

#42 Feature/34 and 대표이미지(썸네일) 첨부
  andcrowd/src/App.js
  andcrowd/src/pages/and/AndCreate.js
  andcrowd/src/pages/and/AndCreateImg.js
  andcrowd/src/pages/and/AndDetail.js
  andcrowd/src/pages/and/AndRole.js
Labels: 임규빈

#47 Feature/39 : 로그인 유저 정보 받아오기
  andcrowd/package-lock.json
  andcrowd/package.json
  andcrowd/src/App.js
  andcrowd/src/pages/and/AndApplicantCreate.js
  andcrowd/src/pages/and/AndBoardCreate.js
  andcrowd/src/pages/and/AndChat.js
  andcrowd/src/pages/and/AndCreate.js
  andcrowd/src/pages/and/AndDetail.js
  andcrowd/src/pages/and/AndQnaCreate.js
  andcrowd/src/pages/and/AndReplyCreate.js
Labels: 임규빈

#30 Feature/26 : AdPayment 결제기능 구현
  andcrowd/src/App.js
  andcrowd/src/pages/crowd/CrowdBoardDetail.js
  andcrowd/src/payment/AdPayment.js
  andcrowd/src/payment/AdPaymentFunction.js
  andcrowd/src/payment/CrowdPaymentFunction.js
Labels: 조승연

#35 Feature/18 : Crowd의 list, create, detail 구현
  .gitignore
  andcrowd/package.json
  andcrowd/src/App.js
  andcrowd/src/pages/CrowdList.js
  andcrowd/src/pages/crowd/CrowdCreate.js
  andcrowd/src/pages/crowd/CrowdDetail.js
  andcrowd/src/pages/crowd/CrowdMainImg.js
  andcrowd/src/pages/crowd/CrowdUpdate.js
  andcrowd/src/styles/crowd/CrowdDetail.module.css
  andcrowd/src/styles/crowd/CrowdList.module.css
  package-lock.json
  package.json
Labels: 오송이

#53 Feature/46 : 모임장 모임관리 페이지
  andcrowd/src/App.js
  andcrowd/src/pages/and/AndApplicantAdmin.js
  andcrowd/src/pages/and/AndDetail.js
  andcrowd/src/pages/and/AndManage.js
Labels: 임규빈

#52 Feature/51: User 정보 가져오기 및 토큰 새로고침 기능 수정
  andcrowd/package-lock.json
  andcrowd/src/App.js
  andcrowd/src/components/Header.js
  andcrowd/src/components/route/LoginRoute.js
  andcrowd/src/components/route/PrivateRoute.js
  andcrowd/src/components/route/SignRoute.js
  andcrowd/src/components/sign/GetNewAccessToken.js
  andcrowd/src/components/sign/Logout.js
  andcrowd/src/components/sign/NaverLogin.js
  andcrowd/src/components/sign/NaverLoginCallback.js
  andcrowd/src/components/sign/SignUpKorName.js
  andcrowd/src/components/sign/checkIsOwner.js
  andcrowd/src/components/sign/isAccessTokenValid.js
  andcrowd/src/components/user/GetUserId.js
  andcrowd/src/components/user/GetUserInfo.js
  andcrowd/src/pages/Test.js
  andcrowd/src/pages/user/MyPage.js
  andcrowd/src/pages/user/Signup.js
  andcrowd/src/pages/user/UserInfoEdit.js
Labels: 김명호

#61 Feature/11: 마이페이지 기능 개선 및 로그인 페이지 디자인 수정
  andcrowd/src/App.css
  andcrowd/src/App.js
  andcrowd/src/components/Header.js
  andcrowd/src/components/route/SignRoute.js
  andcrowd/src/components/sign/SignUpAuthNumber.js
  andcrowd/src/components/sign/SingUpEmail.js
  andcrowd/src/pages/user/FindId.js
  andcrowd/src/pages/user/FindIdOrPassword.js
  andcrowd/src/pages/user/FindPassword.js
  andcrowd/src/pages/user/Login.js
  andcrowd/src/pages/user/MyPage.js
  andcrowd/src/pages/user/Signup.js
  andcrowd/src/pages/user/UserInfoEdit.js
  andcrowd/src/pages/user/UserPasswordChange.js
  andcrowd/src/pages/user/UserResign.js
  andcrowd/src/styles/Login.css
Labels: 김명호

#64 Feature/11: 마이페이지 디자인 수정
  andcrowd/package-lock.json
  andcrowd/src/App.js
  andcrowd/src/components/Header.js
  andcrowd/src/components/route/SignRoute.js
  andcrowd/src/components/user/MyPageCard.js
  andcrowd/src/components/user/MyPageEmptyCard.js
  andcrowd/src/pages/user/MyPage.js
  andcrowd/src/pages/user/ProfileImgEdit.js
  andcrowd/src/pages/user/UserInfoEdit.js
  andcrowd/src/pages/user/UserResign.js
Labels: 김명호

#65 Feature/58 : 채팅 디자인
  andcrowd/package-lock.json
  andcrowd/package.json
  andcrowd/src/components/sign/IsValidAccessToken.js
  andcrowd/src/pages/and/AndChat.js
  andcrowd/src/pages/chat/Chatroom.js
  andcrowd/src/styles/and/AndChat.css
  andcrowd/src/styles/and/Chatroom.css
Labels: 임규빈

#69 Feature/67: 팀 소개 페이지 추가
  andcrowd/package-lock.json
  andcrowd/package.json
  andcrowd/src/App.js
  andcrowd/src/components/Header.js
  andcrowd/src/components/etc/Teammate.js
  andcrowd/src/components/user/MyPageCard.js
  andcrowd/src/components/user/MyPageEmptyCard.js
  andcrowd/src/pages/etc/Team.js
  andcrowd/src/pages/etc/Team2.js
  andcrowd/src/pages/user/MakerPage.js
  andcrowd/src/pages/user/MyPage.js
  andcrowd/src/pages/user/MyPageCardsDetailPage.js
  andcrowd/src/styles/etc/Teammate.css
Labels: 김명호

#70 Feature/66 : 모임 조회수, 찜, 팔로우
  andcrowd/package-lock.json
  andcrowd/src/components/and/AndRightBox.js
  andcrowd/src/pages/and/AndDetail.js
  andcrowd/src/pages/and/AndScroll.js
  andcrowd/src/pages/chat/Chatroom.js
  andcrowd/src/styles/and/Feed.css
Labels: 임규빈

#76 Feature/72 : 모임 qna/board 페이징, qna 디자인
  andcrowd/package-lock.json
  andcrowd/package.json
  andcrowd/src/components/and/userApi.js
  andcrowd/src/pages/and/AndBoard.js
  andcrowd/src/pages/and/AndQna copy.js
  andcrowd/src/pages/and/AndQna.js
  andcrowd/src/pages/and/AndScroll.js
  andcrowd/src/pages/chat/Chatroom.js
  andcrowd/src/styles/and/AndBoard.css
  andcrowd/src/styles/and/AndQna.css
Labels: 임규빈

#78 Feature/71: 관리자 기능 및 페이지 추가, 공지사항 페이지 추가
  andcrowd/.gitignore
  andcrowd/package-lock.json
  andcrowd/package.json
  andcrowd/public/favicon.ico
  andcrowd/public/index.html
  andcrowd/src/&CrowdLogo.png
  andcrowd/src/&CrowdLogo.svg
  andcrowd/src/App.js
  andcrowd/src/components/Footer.js
  andcrowd/src/components/Header.js
  andcrowd/src/components/etc/Teammate.js
  andcrowd/src/components/route/AdminRoute.js
  andcrowd/src/components/user/GetIsUserAdmin.js
  andcrowd/src/components/user/GetUserInfo.js
  andcrowd/src/components/user/MyPageCard.js
  andcrowd/src/components/user/MyPageEmptyCard.js
  andcrowd/src/components/user/UserAndSimple.js
  andcrowd/src/components/user/admin/AdminContents.js
  andcrowd/src/components/user/admin/AdminDeleteButton.js
  andcrowd/src/components/user/admin/AdminInfoCreateButton.js
  andcrowd/src/components/user/admin/AdminInfoEditButton.js
  andcrowd/src/components/user/admin/AdminJudgeButton.js
  andcrowd/src/components/user/admin/AdminMenu.js
  andcrowd/src/components/user/admin/AdminReportProcessButton.js
  andcrowd/src/icon.png
  andcrowd/src/pages/Home.js
  andcrowd/src/pages/and/AndDetail.js
  andcrowd/src/pages/chat/Chatroom.js
  andcrowd/src/pages/etc/Infoboard.js
  andcrowd/src/pages/etc/InfoboardDetail.js
  andcrowd/src/pages/etc/NotFound.js
  andcrowd/src/pages/etc/Team.js
  andcrowd/src/pages/etc/Team2.js
  andcrowd/src/pages/user/Login.js
  andcrowd/src/pages/user/MakerPage.js
  andcrowd/src/pages/user/MyPage.js
  andcrowd/src/pages/user/MyPageCardsDetailPage.js
  andcrowd/src/pages/user/ProfileImgEdit.js
  andcrowd/src/pages/user/Signup.js
  andcrowd/src/pages/user/UserInfoEdit.js
  andcrowd/src/pages/user/admin/AdminMain.js
  andcrowd/src/pages/user/admin/AdminSignup.js
Labels: 김명호

#83 Feature/82 : 도움말에 CLOVA 챗봇 추가
  andcrowd/src/App.js
  andcrowd/src/components/and/AndRightBox.js
  andcrowd/src/components/sign/SignRoute.js
  andcrowd/src/pages/and/AndApplicantAdmin 2.js
  andcrowd/src/pages/and/AndCreate.js
  andcrowd/src/pages/and/AndCreate1.js
  andcrowd/src/pages/and/AndCreateImg 2.js
  andcrowd/src/pages/and/AndCreateImg.js
  andcrowd/src/pages/and/AndCreatePage2.js
  andcrowd/src/pages/and/AndDetail.js
  andcrowd/src/pages/and/AndRole.js
  andcrowd/src/pages/and/AndRoleCreate.js
  andcrowd/src/pages/and/AndScroll.js
  andcrowd/src/pages/crowd/CrowdBoardDeltail.js
  andcrowd/src/pages/etc/Chatbot.js
  andcrowd/src/pages/etc/Help.js
  andcrowd/src/pages/etc/Search.js
  andcrowd/src/styles/and/AndDetail.css
  andcrowd/src/styles/etc/Chatbot.css
Labels: 임규빈

#88 Feature/87 : 모임 카테고리
  andcrowd/package-lock.json
  andcrowd/package.json
  andcrowd/src/category/art.png
  andcrowd/src/category/bibimbap.png
  andcrowd/src/category/creativity.png
  andcrowd/src/category/cutlery.png
  andcrowd/src/category/etc.png
  andcrowd/src/category/gadgets.png
  andcrowd/src/category/languages.png
  andcrowd/src/category/painting.png
  andcrowd/src/category/pets.png
  andcrowd/src/category/running man.png
  andcrowd/src/category/running.png
  andcrowd/src/category/sports.png
  andcrowd/src/category/travel.png
  andcrowd/src/category/traveling.png
  andcrowd/src/components/SearchBar.js
  andcrowd/src/components/and/AndRightBox.js
  andcrowd/src/components/and/AndSearchCard.js
  andcrowd/src/components/and/CountdownTimer.js
  andcrowd/src/components/and/userApi.js
  andcrowd/src/pages/and/AndApplicantCreate.js
  andcrowd/src/pages/and/AndBoardCreate.js
  andcrowd/src/pages/and/AndCreate.js
  andcrowd/src/pages/and/AndCreate1.js
  andcrowd/src/pages/and/AndCreatePage2.js
  andcrowd/src/pages/and/AndQnaCreate.js
  andcrowd/src/pages/and/AndReplyCreate.js
  andcrowd/src/pages/and/AndScroll.js
  andcrowd/src/styles/and/Feed.css
Labels: 임규빈

#90 Feature/79: 소셜 로그인(네이버) 기능 구현
  andcrowd/package-lock.json
  andcrowd/src/App.js
  andcrowd/src/components/Header.js
  andcrowd/src/components/crowd/CrowdCreateImg.js
  andcrowd/src/components/payment/AdPaymentFunction.js
  andcrowd/src/components/payment/CancelPayment.js
  andcrowd/src/components/payment/CrowdPayment.js
  andcrowd/src/components/payment/CrowdPaymentFunction.js
  andcrowd/src/components/payment/CrowdRewardPayment.js
  andcrowd/src/components/route/SignRoute.js
  andcrowd/src/components/sign/IsValidAccessToken.js
  andcrowd/src/components/sign/Logout.js
  andcrowd/src/components/sign/NaverLogin.js
  andcrowd/src/components/sign/NaverLoginCallback.js
  andcrowd/src/components/sign/SignRoute.js
  andcrowd/src/components/sign/checkIsOwner.js
  andcrowd/src/components/sign/oauth2/CallBackFromOAuth.js
  andcrowd/src/components/user/GetIsUserAdmin.js
  andcrowd/src/pages/Home.js
  andcrowd/src/pages/Test.js
  andcrowd/src/pages/and/AndCreatePage2.js
  andcrowd/src/pages/crowd/CrowdCreate.js
  andcrowd/src/pages/crowd/CrowdCreateImg.js
  andcrowd/src/pages/crowd/CrowdRewardCreate.js
  andcrowd/src/pages/crowd/CrowdUploadImg.js
  andcrowd/src/pages/user/Login.js
  andcrowd/src/pages/user/UserInfoEdit.js
  andcrowd/src/pages/user/admin/AdminSignup.js
  andcrowd/src/setupProxy.js
  package-lock.json
Labels: 김명호

#92 Feature/87 : 모임 전체 인원 추가 / 전체 카테고리 추가
  andcrowd/src/category/all.png
  andcrowd/src/components/and/AndRightBox.js
  andcrowd/src/pages/and/AndRoleCreate.js
  andcrowd/src/pages/and/AndScroll.js
  andcrowd/src/styles/and/Feed.css
Labels: 임규빈

#93 Feature/91: Crowd 글쓰기 페이지 및 로직
  andcrowd/src/App.js
  andcrowd/src/components/crowd/CrowdEditor.js
  andcrowd/src/pages/CrowdList.js
  andcrowd/src/pages/and/AndRoleCreate.js
  andcrowd/src/pages/crowd/CrowdCreate.js
  andcrowd/src/pages/crowd/CrowdCreate1.js
  andcrowd/src/pages/crowd/CrowdCreate2.js
  andcrowd/src/pages/crowd/CrowdRewardCreate.js
Labels: 김명호

#96 Feature/89 : 펀딩 조회 필터링 / 검색 페이지에 펀딩 추가 / 모임 스크롤 버튼
  andcrowd/src/components/and/AndRightBox.js
  andcrowd/src/components/and/AndSearchCard.js
  andcrowd/src/pages/CrowdList.js
  andcrowd/src/pages/and/AndCreate1.js
  andcrowd/src/pages/and/AndCreatePage2.js
  andcrowd/src/pages/and/AndRoleCreate.js
  andcrowd/src/pages/and/AndScroll.js
  andcrowd/src/pages/crowd/CrowdCategoryList.js
  andcrowd/src/pages/etc/Search.js
  andcrowd/src/styles/and/Feed.css
Labels: 임규빈

#98 Feature/97 : 모임 마감일 날짜형 / 모임 상세 페이지 수정(신고,지원,역할) / 모임 역할 수정 페이지 추가
  andcrowd/package-lock.json
  andcrowd/src/App.js
  andcrowd/src/components/Header.js
  andcrowd/src/components/and/AndRightBox.js
  andcrowd/src/components/and/CountdownTimer.js
  andcrowd/src/pages/and/AndApplicantCreate.js
  andcrowd/src/pages/and/AndCreatePage2.js
  andcrowd/src/pages/and/AndRoleCreate.js
  andcrowd/src/pages/and/AndRoleUpdate.js
  andcrowd/src/pages/and/AndScroll.js
  andcrowd/src/pages/and/AndUpdate.js
  andcrowd/src/pages/user/MyPage.js
  andcrowd/src/siren.png
  andcrowd/src/styles/and/AndApplicantCreate.css
  andcrowd/src/styles/and/AndDetail.css
  andcrowd/src/styles/and/AndRoleUpdate.css
  andcrowd/src/styles/and/AndUpdate.css
  andcrowd/src/styles/and/Feed.css
Labels: 임규빈

#100 Feature/86 : crowd qna 페이지에서 댓글 생성 기능 구현 외
  andcrowd/package-lock.json
  andcrowd/src/components/crowd/CrowdRightBox.js
  andcrowd/src/pages/CrowdList.js
  andcrowd/src/pages/crowd/CreateImgUploadBtn.js
  andcrowd/src/pages/crowd/CrowdBoardDeltail.js
  andcrowd/src/pages/crowd/CrowdBoardList.js
  andcrowd/src/pages/crowd/CrowdCategoryCreate.js
  andcrowd/src/pages/crowd/CrowdCreate2.js
  andcrowd/src/pages/crowd/CrowdDetail.js
  andcrowd/src/pages/crowd/CrowdQnaCreate.js
  andcrowd/src/pages/crowd/CrowdQnaList.js
  andcrowd/src/pages/crowd/CrowdReplyCreate.js
  andcrowd/src/pages/crowd/CrowdReward.js
  andcrowd/src/pages/crowd/CrowdRewardCreate.js
  andcrowd/src/styles/crowd/CrowdBoardList.module.css
  andcrowd/src/styles/crowd/CrowdQna.css
  andcrowd/src/styles/crowd/CrowdQnaCreate.css
Labels: 오송이

#103 Feature/99 : 챗봇 연결 버튼 / 검색 버튼 / 모임 관리 버튼
  andcrowd/src/App.css
  andcrowd/src/App.js
  andcrowd/src/components/SearchBar.js
  andcrowd/src/components/and/AndRightBox.js
  andcrowd/src/pages/and/AndDetail.js
  andcrowd/src/pages/and/AndScroll.js
  andcrowd/src/pages/etc/HelpChatbot.js
  andcrowd/src/styles/and/AndDetail.css
  andcrowd/src/styles/and/Feed.css
Labels: 임규빈

#105 Feature/102 : crowd의 board, qna 권한설정
  andcrowd/src/pages/crowd/CrowdBoardList.js
  andcrowd/src/pages/crowd/CrowdQnaList.js
Labels: 오송이

#108 Feature/107 : 펀딩 리스트 페이지 수정
  andcrowd/package-lock.json
  andcrowd/package.json
  andcrowd/src/pages/CrowdList.js
  andcrowd/src/pages/and/AndScroll.js
  andcrowd/src/pages/crowd/CrowdCategoryList.js
  andcrowd/src/pages/crowd/CrowdMainImg.js
  andcrowd/src/styles/and/Feed.css
  andcrowd/src/styles/crowd/CrowdList.module.css
Labels: 임규빈

#110 Feature/107 : 펀딩 리스트 찜하기 / 다른 css 수정
  andcrowd/src/components/and/AndRightBox.js
  andcrowd/src/components/and/AndSearchCard.js
  andcrowd/src/pages/CrowdList.js
  andcrowd/src/pages/and/AndApplicantCreate.js
  andcrowd/src/pages/and/AndBoard.js
  andcrowd/src/pages/and/AndBoardCreate.js
  andcrowd/src/pages/and/AndBoardDetail.js
  andcrowd/src/pages/and/AndQna.js
  andcrowd/src/pages/and/AndQnaCreate.js
  andcrowd/src/pages/and/AndRoleCreate.js
  andcrowd/src/pages/and/AndScroll.js
  andcrowd/src/styles/and/AndBoard.css
  andcrowd/src/styles/and/AndBoardDetail.css
  andcrowd/src/styles/and/Feed.css
  andcrowd/src/styles/crowd/CrowdList.module.css
Labels: 임규빈

#111 Feature/106 : crowd의 board(CRUD), qna (CRUD) 구현
  andcrowd/src/components/crowd/CrowdRightBox.js
  andcrowd/src/components/crowd/CrowdTimer2.js
  andcrowd/src/pages/crowd/CrowdBoardDetail.js
  andcrowd/src/pages/crowd/CrowdBoardInsert.js
  andcrowd/src/pages/crowd/CrowdBoardList.js
  andcrowd/src/pages/crowd/CrowdBoardUpdate.js
  andcrowd/src/pages/crowd/CrowdCategoryCreate.js
  andcrowd/src/pages/crowd/CrowdCategoryList.js
  andcrowd/src/pages/crowd/CrowdQnaList.js
  andcrowd/src/pages/crowd/CrowdRewardCreate.js
  andcrowd/src/pages/crowd/CrowdUpdate.js
  andcrowd/src/styles/crowd/CrowdBoardDetail.css
  andcrowd/src/styles/crowd/CrowdBoardInsert.css
  andcrowd/src/styles/crowd/CrowdBoardUpdate.css
  andcrowd/src/styles/crowd/CrowdUpdate.css
Labels: 오송이

#115 Feature/109 : 펀딩 모인금액 추가
  andcrowd/src/components/crowd/CrowdRightBox.js
  andcrowd/src/components/crowd/CrowdTimer.js
  andcrowd/src/pages/CrowdList.js
  andcrowd/src/styles/crowd/CrowdDetail.css
  andcrowd/src/styles/crowd/CrowdList.module.css
Labels: 임규빈

#118 Feature/116 : 펀딩 관리 페이지
  andcrowd/src/App.js
  andcrowd/src/pages/crowd/CrowdManage.js
  andcrowd/src/styles/crowd/CrowdManage.css
Labels: 임규빈

#121 Feature/94: webhook 테스트 및 배포 환경 설정
  andcrowd/Dockerfile
  andcrowd/package.json
  andcrowd/src/App.js
  andcrowd/src/components/crowd/CrowdRightBox.js
  andcrowd/src/components/etc/Loading.js
  andcrowd/src/components/payment/CrowdPayment.js
  andcrowd/src/components/payment/CrowdRewardPayment.js
  andcrowd/src/components/route/AdminRoute.js
  andcrowd/src/components/route/SignRoute.js
  andcrowd/src/components/user/MyPageCard.js
  andcrowd/src/components/user/OrderDetailContent.js
  andcrowd/src/pages/crowd/CrowdManage.js
  andcrowd/src/pages/crowd/CrowdRewardCreate.js
  andcrowd/src/pages/payment/CrowdOrderDetail.js
  andcrowd/src/pages/user/Login.js
  andcrowd/src/pages/user/MakerPage.js
  andcrowd/src/pages/user/MyPage.js
  andcrowd/src/pages/user/MyPageCardsDetailPage.js
  andcrowd/src/pages/user/OrderDetail.js
  andcrowd/src/pages/user/UserInfo.js
  andcrowd/src/pages/user/UserPasswordChange.js
Labels: 김명호

#120 Feature/119 : 펀딩 리스트에 달성금액 추가
  andcrowd/src/pages/CrowdList.js
Labels: 임규빈

#122 Feature/112 : crowd reward 수정 기능 구현
  andcrowd/src/App.js
  andcrowd/src/components/crowd/CrowdRightBox.js
  andcrowd/src/pages/crowd/CrowdQnaCreate.js
  andcrowd/src/pages/crowd/CrowdQnaList.js
  andcrowd/src/pages/crowd/CrowdReward.js
  andcrowd/src/pages/crowd/CrowdRewardUpdate.js
  andcrowd/src/pages/crowd/CrowdRewardUpdateCopy.js
  andcrowd/src/pages/crowd/CrowdRewardcopy.js
  andcrowd/src/pages/crowd/CrowdUpdate.js
  andcrowd/src/share.png
  andcrowd/src/styles/crowd/CrowdDetail.css
  andcrowd/src/styles/crowd/CrowdRewardUpdate.css
  andcrowd/src/styles/crowd/CrowdUpdate.css
Labels: 오송이

#126 Feature/123
  andcrowd/package.json
  andcrowd/src/components/sign/NaverLoginCallback.js
  andcrowd/src/pages/user/Login.js
Labels: 김명호

#125 Feature/119 : 모임 관리 페이지 / 모임 지원 페이지 / 펀딩 관리 페이지 수정
  andcrowd/src/pages/and/AndApplicantCreate.js
  andcrowd/src/pages/and/AndManage.js
  andcrowd/src/pages/and/AndRoleUpdate.js
  andcrowd/src/pages/crowd/CrowdManage.js
  andcrowd/src/styles/and/AndManage.css
Labels: 임규빈

#127 Feature/119 : 펀딩 리워드 수정/삭제/저장 로직 수정
  andcrowd/src/pages/crowd/CrowdRewardUpdate.js
  andcrowd/src/pages/etc/Team.js
Labels: 임규빈

#130 Feature/123: 마이페이지 유저 팔로우 재재수정
  andcrowd/package.json
  andcrowd/src/App.js
  andcrowd/src/components/user/MyPageAvatar.js
  andcrowd/src/pages/user/MyPage.js
  andcrowd/src/pages/user/MyPageAvatarDetailPage.js
Labels: 김명호

#131 Feature/123: Crowd Create CSS 적용
  andcrowd/package.json
  andcrowd/src/components/crowd/CrowdEditor.js
  andcrowd/src/pages/crowd/CrowdCreate.js
  andcrowd/src/pages/crowd/CrowdCreate1.js
  andcrowd/src/pages/crowd/CrowdCreate2.js
  andcrowd/src/styles/crowd/CrowdCreate.css
  andcrowd/src/styles/crowd/CrowdCreate2.css
Labels: 김명호

#132 Feature/123: Crowd Detail css 수정
  andcrowd/package.json
  andcrowd/src/components/crowd/CrowdRightBox.js
  andcrowd/src/styles/crowd/CrowdDetail.css
Labels: 김명호

#129 Feature/119 : 펀딩 상세 페이지 팔로우 기능 수정
  andcrowd/src/components/crowd/CrowdRightBox.js
Labels: 임규빈

#139 Feature/119 : 챗봇 1:1로 변경
  andcrowd/src/App.js
  andcrowd/src/components/and/AndRightBox.js
  andcrowd/src/components/crowd/CrowdRightBox.js
  andcrowd/src/pages/CrowdList.js
  andcrowd/src/pages/and/AndDetail.js
  andcrowd/src/pages/and/AndScroll.js
  andcrowd/src/pages/chat/Chatroom.js
  andcrowd/src/pages/crowd/CrowdDetail.js
  andcrowd/src/pages/crowd/CrowdQnaList.js
  andcrowd/src/pages/etc/HelpChatbot.js
  andcrowd/src/pages/etc/Team.js
  andcrowd/src/styles/and/Chatroom.css
  andcrowd/src/styles/etc/Chatbot.css
Labels: 임규빈

#141 Feature/123: 로그인 및 회원가입 css 수정
  andcrowd/src/components/Header.js
  andcrowd/src/pages/and/AndChat.js
  andcrowd/src/pages/chat/Chatroom.js
  andcrowd/src/pages/etc/HelpChatbot.js
  andcrowd/src/pages/user/Login.js
  andcrowd/src/pages/user/Signup.js
  andcrowd/src/styles/Login.css
Labels: 김명호

#142 Feature/119 : 잘못된 주소 리다이렉트
  andcrowd/src/pages/CrowdList.js
  andcrowd/src/pages/and/AndApplicant.js
  andcrowd/src/pages/and/AndApplicantAdmin.js
  andcrowd/src/pages/and/AndApplicantDetail.js
  andcrowd/src/pages/and/AndApplicantUpdate.js
  andcrowd/src/pages/and/AndBoard.js
  andcrowd/src/pages/and/AndBoardDetail.js
  andcrowd/src/pages/and/AndDetail.js
  andcrowd/src/pages/and/AndManage.js
  andcrowd/src/pages/and/AndMember.js
  andcrowd/src/pages/and/AndMemberDetail.js
  andcrowd/src/pages/and/AndQna.js
  andcrowd/src/pages/and/AndQnaDetail.js
  andcrowd/src/pages/and/AndRole.js
  andcrowd/src/pages/and/AndRoleDetail.js
  andcrowd/src/pages/and/AndScroll.js
Labels: 임규빈

#143 Feature/119 : 잘못된 채팅 주소 404 리다이렉트
  andcrowd/src/pages/and/AndChat.js
Labels: 임규빈
