Repository kmaengggong/AndCrowd-Frontend, pull requests merged in 2023-08, with the labels that each got.

#16 Feature/5: And 프론트 임시 페이지
  andcrowd/package-lock.json
  andcrowd/package.json
  andcrowd/src/App.js
  andcrowd/src/pages/AndList.js
  andcrowd/src/pages/and/AndBoard.js
  andcrowd/src/pages/and/AndBoardCreate.js
  andcrowd/src/pages/and/AndBoardDetail.js
  andcrowd/src/pages/and/AndBoardUpdate.js
  andcrowd/src/pages/and/AndCreate.js
  andcrowd/src/pages/and/AndDetail.js
  andcrowd/src/pages/and/AndQna.js
  andcrowd/src/pages/and/AndQnaCreate.js
  andcrowd/src/pages/and/AndQnaDetail.js
  andcrowd/src/pages/and/AndQnaUpdate.js
  andcrowd/src/pages/and/AndRole.js
  andcrowd/src/pages/and/AndRoleCreate.js
  andcrowd/src/pages/and/AndRoleDetail.js
  andcrowd/src/pages/and/AndRoleUpdate.js
  andcrowd/src/pages/and/AndScroll button.js
  andcrowd/src/pages/and/AndScroll.js
  andcrowd/src/pages/and/AndUpdate.js
  andcrowd/src/pages/and/Feed.css
Labels: 임규빈

#19 Feature/7 : CrowdBoard의 CRUD구현
  andcrowd/src/App.js
  andcrowd/src/pages/crowd/CrowdBoardDeltail.js
  andcrowd/src/pages/crowd/CrowdBoardInsert.js
  andcrowd/src/pages/crowd/CrowdBoardList.js
  andcrowd/src/pages/crowd/CrowdBoardUpdate.js
  andcrowd/src/styles/crowd/CrowdBoardList.module.css
Labels: 조승연

#23 Feature/22 : 푸터,네비게이션바 디자인 적용
  andcrowd/.gitignore
  andcrowd/public/index.html
  andcrowd/public/naverLoginButton.png
  andcrowd/src/App.css
  andcrowd/src/App.js
  andcrowd/src/components/Footer.js
  andcrowd/src/components/Header.js
  andcrowd/src/components/NaverLogin.js
  andcrowd/src/components/Navigation.js
  andcrowd/src/components/user/UserAndSimple.js
  andcrowd/src/index.css
  andcrowd/src/pages/CrowdList.js
  andcrowd/src/pages/Help.js
  andcrowd/src/pages/Login.js
  andcrowd/src/pages/MyPage.js
  andcrowd/src/pages/Signup.js
  andcrowd/src/pages/Team.js
  andcrowd/src/styles/Footer.css
  andcrowd/src/styles/Header.css
  andcrowd/src/styles/Header.module.css
  andcrowd/src/styles/Navigation.module.css
Labels: 양현성

#27 Feature/24 : 로그인 페이지 디자인
  andcrowd/public/naverLoginButton2.png
  andcrowd/src/components/NaverLogin.js
  andcrowd/src/pages/Login.js
  andcrowd/src/styles/Footer.css
  andcrowd/src/styles/Login.css
Labels: 양현성

#25 Feature/20 : Crowd의 결제기능 구현(Frontend)
  andcrowd/public/index.html
  andcrowd/src/App.js
  andcrowd/src/payment/AdPayment.js
  andcrowd/src/payment/CrowdPayment.js
Labels: 조승연
